server:
  port: 1885

spring:
  application:
    # 服务与服务之间相互调用一般都是根据这个name 。
    name: auth-service-dev
  datasource:
    url: jdbc:mysql://47.99.211.9:3306/auth?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: ENC(Q+Pn4LhPX8OZaLFS6EuoEg==)
    password: ENC(Q+Pn4LhPX8OZaLFS6EuoEg==)
    driver-class-name: com.mysql.jdbc.Driver
#    springboot2.0+默认为hikari 此配置项可删除
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  redis:
      #数据库索引
      database: 0
      host: 47.99.211.9
      port: 6379
      password: ENC(Q+Pn4LhPX8OZaLFS6EuoEg==)
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
      #连接超时时间
      timeout: 10000

mybatis:
  mapper-locations: classpath:/mapper/*

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jasypt:
  encryptor:
#    加解密的时候使用的密钥(密码盐)
    password: 123456