server:
  port: 1990

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cms-service
  datasource:
    url: jdbc:mysql://47.99.211.9:3306/auth?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: ENC(Q+Pn4LhPX8OZaLFS6EuoEg==)
    password: ENC(Q+Pn4LhPX8OZaLFS6EuoEg==)
    driver-class-name: com.mysql.jdbc.Driver
#    springboot2.0+默认为hikari 此配置项可删除
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

jasypt:
  encryptor:
#    加解密的时候使用的密钥(密码盐)
    password: 123456

feign:
  hystrix:
    enabled: true
